name: MooImageTip
author: lorenzo.stanco
category: Media
tags: [image, tooltip, tip, link, thumbnails]
demo: http://jsfiddle.net/znTbE/389/
docs: http://wiki.github.com/lorenzos/MooImageTip/docs
current: 1.7
